# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
# list any PHP version you want to test against
php:
  - 5.4
env:
  - DB=redis

before_script: 
  - phpenv config-add test/php.config  

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: php test/runtests.php

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "normandiggs@gmail.com"